apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seedling.fullname" . }}
  labels:
    {{- include "seedling.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "seedling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "seedling.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "seedling.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.image.repository }}/seedling-backend:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.backend.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

