apiVersion: v1
kind: Service
metadata:
  name: {{ include "seedling.fullname" . }}
  labels:
    {{- include "seedling.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.backend.type }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seedling.selectorLabels" . | nindent 4 }}
